# This is a basic workflow to help you get started with Actions

name: Deploy to Server

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  SCP:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copy via ssh
      uses: garygrossgarten/github-action-scp@v0.6.0  
      with:
          local: public
          remote: ${{ secrets.PATH }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
